namespace ClashSharp.Model;

/// <summary>Represents local mihomo configuration file state managed by Clash#.</summary>
/// <param name="DirectoryPath">Absolute configuration directory path; never null.</param>
/// <param name="ConfigPath">Absolute configuration file path; never null.</param>
/// <param name="Exists">True when the configuration file currently exists.</param>
/// <remarks>
/// Invariants: Path values are absolute strings generated by <see cref="Service.CoreConfigurationService"/>.
/// Thread safety: Immutable value type and inherently thread-safe after construction.
/// Side effects: None.
/// </remarks>
public readonly record struct CoreConfigurationState(string DirectoryPath, string ConfigPath, bool Exists)
{
    /// <summary>Gets the immutable user-data generation containing this file, or null for the legacy root.</summary>
    public System.Guid? DataGenerationId { get; init; }
}
