Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

<#
.SYNOPSIS
Requires one Windows Sandbox report to prove the exact requested scenario passed.
.DESCRIPTION
Validates the exact report schema, scenario identity, run identity, timestamps, guest environment,
terminal status, step evidence, checks, and failure field. Only a complete passed report with at
least one passed step and one check is accepted; unknown fields, skipped, failed, timed-out, empty,
or mismatched reports throw.
.PARAMETER Report
Deserialized scenario report received from the sandbox guest.
.PARAMETER ExpectedScenario
Exact scenario name selected by the host.
.PARAMETER ExpectedRunId
Exact unique run identifier generated by the host.
#>
function Assert-SandboxScenarioReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNull()]
        [object]$Report,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$ExpectedScenario,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$ExpectedRunId
    )

    if ($Report -isnot [System.Management.Automation.PSCustomObject]) {
        throw "Sandbox report must be a JSON object."
    }

    $requiredProperties = @(
        "schemaVersion",
        "scenario",
        "runId",
        "status",
        "startedAt",
        "finishedAt",
        "environment",
        "steps",
        "checks",
        "failure"
    )
    $actualPropertyNames = @($Report.PSObject.Properties.Name)
    foreach ($propertyName in $requiredProperties) {
        if ($actualPropertyNames -cnotcontains $propertyName) {
            throw "Sandbox report is missing required property '$propertyName'."
        }
    }

    $unexpectedProperties = @(
        $actualPropertyNames | Where-Object { $requiredProperties -cnotcontains $_ }
    )
    if ($unexpectedProperties.Count -ne 0) {
        throw "Sandbox report contains unsupported properties: $($unexpectedProperties -join ', ')."
    }

    $schemaVersion = $Report.schemaVersion
    if (($schemaVersion -isnot [int] -and $schemaVersion -isnot [long]) -or $schemaVersion -ne 1) {
        throw "Sandbox report has unsupported schemaVersion '$schemaVersion'."
    }

    $actualScenario = [string]$Report.scenario
    if (-not [string]::Equals($actualScenario, $ExpectedScenario, [StringComparison]::Ordinal)) {
        throw "Sandbox report scenario mismatch. Expected '$ExpectedScenario', got '$actualScenario'."
    }

    $actualRunId = [string]$Report.runId
    if (-not [string]::Equals($actualRunId, $ExpectedRunId, [StringComparison]::Ordinal)) {
        throw "Sandbox report runId mismatch. Expected '$ExpectedRunId', got '$actualRunId'."
    }

    $status = [string]$Report.status
    if (-not [string]::Equals($status, "passed", [StringComparison]::Ordinal)) {
        throw "Sandbox scenario '$ExpectedScenario' did not pass; terminal status was '$status'."
    }

    [DateTimeOffset]$startedAt = [DateTimeOffset]::MinValue
    [DateTimeOffset]$finishedAt = [DateTimeOffset]::MinValue
    $timestampStyle = [Globalization.DateTimeStyles]::RoundtripKind
    $startedAtValid = [DateTimeOffset]::TryParse(
        [string]$Report.startedAt,
        [Globalization.CultureInfo]::InvariantCulture,
        $timestampStyle,
        [ref]$startedAt)
    $finishedAtValid = [DateTimeOffset]::TryParse(
        [string]$Report.finishedAt,
        [Globalization.CultureInfo]::InvariantCulture,
        $timestampStyle,
        [ref]$finishedAt)
    if (-not $startedAtValid -or
        -not $finishedAtValid -or
        $finishedAt -lt $startedAt) {
        throw "Sandbox scenario '$ExpectedScenario' has invalid report timestamps."
    }

    $environment = $Report.environment
    if ($environment -isnot [System.Management.Automation.PSCustomObject]) {
        throw "Sandbox scenario '$ExpectedScenario' has invalid environment evidence."
    }

    $requiredEnvironmentProperties = @("computerName", "userName", "osBuild", "architecture")
    $environmentPropertyNames = @($environment.PSObject.Properties.Name)
    foreach ($propertyName in $requiredEnvironmentProperties) {
        $hasProperty = $environmentPropertyNames -ccontains $propertyName
        $hasValue = $hasProperty -and
            -not [string]::IsNullOrWhiteSpace([string]$environment.$propertyName)
        if (-not $hasProperty -or -not $hasValue) {
            throw "Sandbox scenario '$ExpectedScenario' has incomplete environment evidence."
        }
    }

    if (@($environmentPropertyNames | Where-Object {
                $requiredEnvironmentProperties -cnotcontains $_
            }).Count -ne 0) {
        throw "Sandbox scenario '$ExpectedScenario' has unsupported environment evidence."
    }

    $stepEvidence = @($Report.steps)
    if ($stepEvidence.Count -eq 0) {
        throw "Sandbox scenario '$ExpectedScenario' reported no executed steps."
    }

    foreach ($step in $stepEvidence) {
        if ($step -isnot [System.Management.Automation.PSCustomObject]) {
            throw "Sandbox scenario '$ExpectedScenario' contains missing or non-passed step evidence."
        }

        $requiredStepProperties = @(
            "name",
            "status",
            "startedAt",
            "finishedAt",
            "durationMs",
            "error"
        )
        $stepPropertyNames = @($step.PSObject.Properties.Name)
        foreach ($propertyName in $requiredStepProperties) {
            if ($stepPropertyNames -cnotcontains $propertyName) {
                throw "Sandbox scenario '$ExpectedScenario' contains incomplete step evidence."
            }
        }

        if (@($stepPropertyNames | Where-Object {
                    $requiredStepProperties -cnotcontains $_
                }).Count -ne 0) {
            throw "Sandbox scenario '$ExpectedScenario' contains unsupported step evidence."
        }

        $stepName = [string]$step.name
        $stepStatus = [string]$step.status
        $stepPassed = [string]::Equals($stepStatus, "passed", [StringComparison]::Ordinal)
        if ([string]::IsNullOrWhiteSpace($stepName) -or
            -not $stepPassed -or
            $null -ne $step.error) {
            throw "Sandbox scenario '$ExpectedScenario' contains missing or non-passed step evidence."
        }

        [DateTimeOffset]$stepStartedAt = [DateTimeOffset]::MinValue
        [DateTimeOffset]$stepFinishedAt = [DateTimeOffset]::MinValue
        $stepStartedAtValid = [DateTimeOffset]::TryParse(
            [string]$step.startedAt,
            [Globalization.CultureInfo]::InvariantCulture,
            $timestampStyle,
            [ref]$stepStartedAt)
        $stepFinishedAtValid = [DateTimeOffset]::TryParse(
            [string]$step.finishedAt,
            [Globalization.CultureInfo]::InvariantCulture,
            $timestampStyle,
            [ref]$stepFinishedAt)
        if (-not $stepStartedAtValid -or
            -not $stepFinishedAtValid -or
            $stepStartedAt -lt $startedAt -or
            $stepFinishedAt -lt $stepStartedAt -or
            $stepFinishedAt -gt $finishedAt) {
            throw "Sandbox scenario '$ExpectedScenario' contains invalid step timestamps."
        }

        $durationMs = $step.durationMs
        if (($durationMs -isnot [int] -and $durationMs -isnot [long]) -or $durationMs -lt 0) {
            throw "Sandbox scenario '$ExpectedScenario' contains invalid step duration evidence."
        }
    }

    if ($Report.checks -isnot [System.Management.Automation.PSCustomObject]) {
        throw "Sandbox scenario '$ExpectedScenario' reported no verified checks."
    }

    $checkPropertyNames = @($Report.checks.PSObject.Properties.Name)
    if ($checkPropertyNames.Count -eq 0 -or $checkPropertyNames -ccontains "notExecuted") {
        throw "Sandbox scenario '$ExpectedScenario' reported no verified checks."
    }

    switch ($ExpectedScenario) {
        "install-only" {
            if ($checkPropertyNames.Count -ne 1 -or
                $checkPropertyNames -cnotcontains "package") {
                throw "Sandbox install-only report contains unsupported checks."
            }

            $package = $Report.checks.package
            if ($package -isnot [System.Management.Automation.PSCustomObject]) {
                throw "Sandbox install-only report has invalid package evidence."
            }

            $requiredPackageProperties = @(
                "installed",
                "name",
                "fullName",
                "version",
                "source",
                "dependencyCount"
            )
            $packagePropertyNames = @($package.PSObject.Properties.Name)
            foreach ($propertyName in $requiredPackageProperties) {
                if ($packagePropertyNames -cnotcontains $propertyName) {
                    throw "Sandbox install-only report has incomplete package evidence."
                }
            }

            if (@($packagePropertyNames | Where-Object {
                        $requiredPackageProperties -cnotcontains $_
                    }).Count -ne 0) {
                throw "Sandbox install-only report has unsupported package evidence."
            }

            $expectedPackageName = "67dc1dc3-13fd-46c5-84f4-2932d94b566f"
            $packageSource = [string]$package.source
            $hasSupportedPackageExtension =
                $packageSource.EndsWith(".msix", [StringComparison]::OrdinalIgnoreCase) -or
                $packageSource.EndsWith(".msixbundle", [StringComparison]::OrdinalIgnoreCase)
            $dependencyCount = $package.dependencyCount
            if ($package.installed -isnot [bool] -or
                -not $package.installed -or
                -not [string]::Equals(
                    [string]$package.name,
                    $expectedPackageName,
                    [StringComparison]::Ordinal) -or
                -not ([string]$package.fullName).StartsWith(
                    "${expectedPackageName}_",
                    [StringComparison]::Ordinal) -or
                [string]::IsNullOrWhiteSpace([string]$package.version) -or
                [string]::IsNullOrWhiteSpace($packageSource) -or
                -not $hasSupportedPackageExtension -or
                ($dependencyCount -isnot [int] -and $dependencyCount -isnot [long]) -or
                $dependencyCount -lt 0) {
                throw "Sandbox install-only report has invalid package evidence."
            }
        }
        default {
            throw "Sandbox scenario '$ExpectedScenario' has no passing evidence contract."
        }
    }

    if ($null -ne $Report.failure) {
        throw "Sandbox scenario '$ExpectedScenario' reported a failure despite passed status."
    }
}

Export-ModuleMember -Function Assert-SandboxScenarioReport
