#Requires -Version 5.1

<#
.SYNOPSIS
    Regenerates the installer ICO from its actual WPF vector resource.
.DESCRIPTION
    Uses Windows PowerShell 5.1 and the in-box WPF software rasterizer without
    opening a window or launching the installer. Keeps the canonical 1024-unit
    canvas and applies explicit optical adjustments to the smallest frames.
    Writes uncompressed 32-bit DIB frames with alpha and an AND mask, avoiding
    image encoder metadata, compression versions and external rendering tools.
.PARAMETER OutputPath
    ICO destination. Defaults to the installer's checked-in application icon.
.PARAMETER PreviewDirectory
    Optional directory for PNG previews of every frame and the unhinted master.
.PARAMETER Verify
    Compares generated bytes with OutputPath and fails without replacing it.
.EXAMPLE
    powershell.exe -NoProfile -File eng/Generate-InstallerIcon.ps1 -Verify
#>
[CmdletBinding()]
param(
    [ValidateNotNullOrEmpty()]
    [string]$OutputPath,

    [ValidateNotNullOrEmpty()]
    [string]$PreviewDirectory,

    [switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ($PSVersionTable.PSEdition -ne 'Desktop' -or
    [Threading.Thread]::CurrentThread.GetApartmentState() -ne 'STA') {
    throw 'Run with Windows PowerShell 5.1 in STA mode for the canonical WPF renderer.'
}

Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName PresentationFramework

<#
.SYNOPSIS
    Loads only the installer's vector drawing from its trusted source resource.
.DESCRIPTION
    Rejects DTDs and missing or unexpected geometry layers before rendering.
    The SVG-to-WPF geometry contract is checked by Presentation tests.
.PARAMETER Path
    Absolute path to InstallerTheme.xaml in this repository.
#>
function Import-InstallerDrawing {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Path)

    $settings = [Xml.XmlReaderSettings]::new()
    $settings.DtdProcessing = [Xml.DtdProcessing]::Prohibit
    $settings.XmlResolver = $null
    $reader = [Xml.XmlReader]::Create($Path, $settings)
    try {
        $document = [Xml.XmlDocument]::new()
        $document.XmlResolver = $null
        $document.Load($reader)
    }
    finally {
        $reader.Dispose()
    }

    $namespaces = [Xml.XmlNamespaceManager]::new($document.NameTable)
    $namespaces.AddNamespace('p', 'http://schemas.microsoft.com/winfx/2006/xaml/presentation')
    $namespaces.AddNamespace('x', 'http://schemas.microsoft.com/winfx/2006/xaml')
    $nodes = $document.SelectNodes(
        "//p:DrawingImage[@x:Key='ClashSharpBrandMark']/p:DrawingImage.Drawing/p:DrawingGroup",
        $namespaces)
    if ($nodes.Count -ne 1) {
        throw 'Expected one canonical installer brand drawing.'
    }

    $drawing = [Windows.Markup.XamlReader]::Parse($nodes[0].OuterXml)
    if ($drawing -isnot [Windows.Media.DrawingGroup] -or $drawing.Children.Count -ne 11) {
        throw 'Expected the hexagon, five shadow layers and five white mark layers.'
    }

    for ($index = 0; $index -lt $drawing.Children.Count; $index++) {
        $layer = $drawing.Children[$index]
        if ($layer -isnot [Windows.Media.GeometryDrawing]) {
            throw 'Every brand layer must be a vector geometry drawing.'
        }
        if ($index -ge 6 -and $layer.Brush.Color -ne [Windows.Media.Colors]::White) {
            throw 'The final five brand layers must be the white hash and C.'
        }
    }

    $drawing.Freeze()
    return $drawing
}

<#
.SYNOPSIS
    Renders one transparent icon frame directly from the vector resource.
.DESCRIPTION
    At 16 through 32 pixels, snaps both crossbars to whole pixel boundaries
    and enlarges the canonical C to an optical footprint of at least 2 by 2
    pixels (2 by 3 from 20 pixels), keeping it below the lower crossbar.
    Larger frames preserve the master geometry without optical adjustments.
.PARAMETER Master
    Frozen WPF drawing loaded from the installer theme.
.PARAMETER Size
    Width and height of the output bitmap in pixels.
.PARAMETER Unhinted
    Preserves exact master geometry for comparison previews.
#>
function New-InstallerIconBitmap {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][Windows.Media.DrawingGroup]$Master,
        [Parameter(Mandatory)][ValidateRange(16, 256)][int]$Size,
        [switch]$Unhinted
    )

    $drawing = $Master.Clone()
    $scale = $Size / 1024.0
    if ($Size -le 32 -and -not $Unhinted) {
        foreach ($index in @(8, 9)) {
            $bounds = $drawing.Children[$index].Geometry.Bounds
            $left = [Math]::Round($bounds.Left * $scale)
            $top = [Math]::Round($bounds.Top * $scale)
            $width = [Math]::Round($bounds.Right * $scale) - $left
            $height = [Math]::Max(1, [Math]::Round($bounds.Height * $scale))
            $rectangle = [Windows.Rect]::new(
                $left / $scale, $top / $scale, $width / $scale, $height / $scale)
            $drawing.Children[$index].Geometry = [Windows.Media.RectangleGeometry]::new($rectangle)
        }

        $suffix = $drawing.Children[10].Geometry
        $bounds = $suffix.Bounds
        $width = [Math]::Max(2, $bounds.Width * $scale)
        $minimumHeight = 3
        if ($Size -eq 16) { $minimumHeight = 2 }
        $height = [Math]::Max($minimumHeight, $bounds.Height * $scale)
        $right = $bounds.Right * $scale
        $bottom = [Math]::Ceiling($bounds.Bottom * $scale)
        $transform = [Windows.Media.Matrix]::new(
            $width / ($bounds.Width * $scale), 0,
            0, $height / ($bounds.Height * $scale),
            ($right - $width) / $scale - $bounds.Left * $width / ($bounds.Width * $scale),
            ($bottom - $height) / $scale - $bounds.Top * $height / ($bounds.Height * $scale))
        $suffix.Transform = [Windows.Media.MatrixTransform]::new($transform)
    }

    $drawing.Transform = [Windows.Media.ScaleTransform]::new($scale, $scale)
    $drawing.Freeze()
    $visual = [Windows.Media.DrawingVisual]::new()
    $context = $visual.RenderOpen()
    try {
        $context.DrawDrawing($drawing)
    }
    finally {
        $context.Close()
    }

    $bitmap = [Windows.Media.Imaging.RenderTargetBitmap]::new(
        $Size, $Size, 96, 96, [Windows.Media.PixelFormats]::Pbgra32)
    $bitmap.Render($visual)
    $bitmap.Freeze()
    return $bitmap
}

<#
.SYNOPSIS
    Encodes one bitmap as a metadata-free ICO DIB frame.
.DESCRIPTION
    Stores straight BGRA pixels bottom-up, followed by a DWORD-aligned AND
    mask. Fully transparent pixels have zero RGB and a set mask bit.
.PARAMETER Bitmap
    Square WPF bitmap to encode.
#>
function ConvertTo-InstallerIconFrame {
    [CmdletBinding()]
    param([Parameter(Mandatory)][Windows.Media.Imaging.BitmapSource]$Bitmap)

    $size = $Bitmap.PixelWidth
    $straight = [Windows.Media.Imaging.FormatConvertedBitmap]::new(
        $Bitmap, [Windows.Media.PixelFormats]::Bgra32, $null, 0)
    $stride = $size * 4
    $pixels = [byte[]]::new($stride * $size)
    $straight.CopyPixels($pixels, $stride, 0)
    $maskStride = [int]([Math]::Ceiling($size / 32.0) * 4)
    $mask = [byte[]]::new($maskStride * $size)
    for ($y = 0; $y -lt $size; $y++) {
        for ($x = 0; $x -lt $size; $x++) {
            $pixel = $y * $stride + $x * 4
            if ($pixels[$pixel + 3] -eq 0) {
                $pixels[$pixel] = 0
                $pixels[$pixel + 1] = 0
                $pixels[$pixel + 2] = 0
                $maskIndex = ($size - 1 - $y) * $maskStride + [int][Math]::Floor($x / 8.0)
                $mask[$maskIndex] = $mask[$maskIndex] -bor (128 -shr ($x % 8))
            }
        }
    }

    $stream = [IO.MemoryStream]::new()
    $writer = [IO.BinaryWriter]::new($stream)
    try {
        $writer.Write([int]40)
        $writer.Write([int]$size)
        $writer.Write([int]($size * 2))
        $writer.Write([uint16]1)
        $writer.Write([uint16]32)
        $writer.Write([int]0)
        $writer.Write([int]($pixels.Length + $mask.Length))
        foreach ($unused in 1..4) { $writer.Write([int]0) }
        for ($y = $size - 1; $y -ge 0; $y--) {
            $writer.Write($pixels, $y * $stride, $stride)
        }
        $writer.Write($mask)
        $writer.Flush()
        return ,$stream.ToArray()
    }
    finally {
        $writer.Dispose()
        $stream.Dispose()
    }
}

<#
.SYNOPSIS
    Saves a generated bitmap for visual review.
.DESCRIPTION
    PNG previews are review artifacts and do not participate in ICO encoding.
.PARAMETER Bitmap
    Bitmap to preview.
.PARAMETER Path
    Absolute destination inside the requested preview directory.
#>
function Export-InstallerIconPreview {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][Windows.Media.Imaging.BitmapSource]$Bitmap,
        [Parameter(Mandatory)][string]$Path
    )

    $encoder = [Windows.Media.Imaging.PngBitmapEncoder]::new()
    $encoder.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($Bitmap))
    $stream = [IO.File]::Create($Path)
    try { $encoder.Save($stream) }
    finally { $stream.Dispose() }
}

$repositoryRoot = Split-Path -Parent $PSScriptRoot
if (-not $PSBoundParameters.ContainsKey('OutputPath')) {
    $OutputPath = Join-Path $repositoryRoot 'ClashSharp/Installer/LogoInstaller.ico'
}
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
if ($PSBoundParameters.ContainsKey('PreviewDirectory')) {
    $PreviewDirectory = [IO.Path]::GetFullPath($PreviewDirectory)
    $null = [IO.Directory]::CreateDirectory($PreviewDirectory)
}

$themePath = Join-Path $repositoryRoot 'ClashSharp/ClashSharp.Installer/Themes/InstallerTheme.xaml'
$master = Import-InstallerDrawing -Path $themePath
$sizes = @(16, 20, 24, 32, 40, 48, 64, 128, 256)
$frames = [Collections.Generic.List[byte[]]]::new()
foreach ($size in $sizes) {
    $bitmap = New-InstallerIconBitmap -Master $master -Size $size
    $frames.Add((ConvertTo-InstallerIconFrame -Bitmap $bitmap))
    if ($PreviewDirectory) {
        Export-InstallerIconPreview -Bitmap $bitmap -Path (Join-Path $PreviewDirectory "frame-$size.png")
        if ($size -le 32) {
            $unhinted = New-InstallerIconBitmap -Master $master -Size $size -Unhinted
            Export-InstallerIconPreview -Bitmap $unhinted -Path (Join-Path $PreviewDirectory "unhinted-$size.png")
        }
    }
}

$stream = [IO.MemoryStream]::new()
$writer = [IO.BinaryWriter]::new($stream)
try {
    $writer.Write([uint16]0)
    $writer.Write([uint16]1)
    $writer.Write([uint16]$sizes.Count)
    $offset = 6 + 16 * $sizes.Count
    for ($index = 0; $index -lt $sizes.Count; $index++) {
        $dimension = [byte]($sizes[$index] % 256)
        $writer.Write($dimension)
        $writer.Write($dimension)
        $writer.Write([uint16]0)
        $writer.Write([uint16]1)
        $writer.Write([uint16]32)
        $writer.Write([int]$frames[$index].Length)
        $writer.Write([int]$offset)
        $offset += $frames[$index].Length
    }
    foreach ($frame in $frames) { $writer.Write($frame) }
    $writer.Flush()
    $bytes = $stream.ToArray()
}
finally {
    $writer.Dispose()
    $stream.Dispose()
}

if ($Verify) {
    $existing = [IO.File]::ReadAllBytes($OutputPath)
    if ($existing.Length -ne $bytes.Length -or
        [Convert]::ToBase64String($existing) -cne [Convert]::ToBase64String($bytes)) {
        throw 'Installer ICO differs from its vector source. Regenerate and review every frame.'
    }
}
else {
    [IO.File]::WriteAllBytes($OutputPath, $bytes)
}

Write-Output ('Installer icon: {0} frames ({1}), {2} bytes; SHA-256 {3}.' -f
    $sizes.Count, ($sizes -join ', '), $bytes.Length,
    (Get-FileHash -LiteralPath $OutputPath -Algorithm SHA256).Hash.ToLowerInvariant())
