<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ClashSharp</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClashSharp.Application\ClashSharp.Application.csproj" />
  </ItemGroup>
</Project>
