[package]
name = "clashsharp-installer"
version = "1.0.0"
edition = "2024"
description = "Clash# Native Windows Installer"

[[bin]]
name = "ClashSharp-Installer"
path = "src/main.rs"

[dependencies]
slint = { version = "1", default-features = false, features = [
    "accessibility",
    "backend-winit",
    "compat-1-2",
    "renderer-femtovg",
    "renderer-software",
    "std",
    "system-tray",
] }

[build-dependencies]
slint-build = "1"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
