/*
 * Core Configuration Service
 * Provides local mihomo configuration directory management and default configuration generation
 *
 * @author: WaterRun
 * @file: Service/CoreConfigurationService.cs
 * @date: 2026-06-15
 */

using System;
using System.Globalization;
using System.IO;
using System.Text;
using ClashSharp.Model;
using Windows.Storage;

namespace ClashSharp.Service;

/// <summary>Manages local mihomo configuration paths and default configuration generation.</summary>
/// <remarks>
/// Invariants: The configuration directory is created before a default configuration is written.
/// Thread safety: Public mutation methods serialize filesystem access through a private lock.
/// Side effects: Creates directories and writes the local mihomo configuration file.
/// </remarks>
public sealed class CoreConfigurationService
{
    /// <summary>Shared singleton instance created once at type initialization.</summary>
    /// <value>A non-null <see cref="CoreConfigurationService"/> instance.</value>
    public static CoreConfigurationService Instance { get; } = new();

    /// <summary>Synchronization object guarding filesystem mutations for this service lifetime.</summary>
    private readonly object _syncLock = new();

    /// <summary>Absolute directory path for mihomo runtime configuration.</summary>
    private readonly string _configurationDirectoryPath;

    /// <summary>Absolute file path for the generated mihomo configuration.</summary>
    private readonly string _configurationFilePath;

    /// <summary>Initializes the configuration service and resolves configuration paths.</summary>
    private CoreConfigurationService()
    {
        _configurationDirectoryPath = Path.Combine(ResolveDataDirectory(), "mihomo");
        _configurationFilePath = Path.Combine(_configurationDirectoryPath, "config.yaml");
    }

    /// <summary>Gets the current local mihomo configuration state.</summary>
    /// <returns>A <see cref="CoreConfigurationState"/> snapshot for the managed configuration file.</returns>
    public CoreConfigurationState GetState()
    {
        return new CoreConfigurationState(
            _configurationDirectoryPath,
            _configurationFilePath,
            File.Exists(_configurationFilePath));
    }

    /// <summary>Ensures the local configuration directory and default configuration file exist.</summary>
    /// <returns>A <see cref="CoreConfigurationState"/> snapshot after the ensure operation completes.</returns>
    public CoreConfigurationState EnsureDefaultConfiguration()
    {
        return EnsureConfiguration(ClashSharpMode.Standby);
    }

    /// <summary>Ensures the local configuration directory and managed configuration file match <paramref name="mode"/>.</summary>
    /// <param name="mode">Master takeover mode whose mihomo mode should be represented in the generated configuration.</param>
    /// <returns>A <see cref="CoreConfigurationState"/> snapshot after the ensure operation completes.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="mode"/> cannot be mapped to a mihomo mode.</exception>
    public CoreConfigurationState EnsureConfiguration(ClashSharpMode mode)
    {
        lock (_syncLock)
        {
            Directory.CreateDirectory(_configurationDirectoryPath);

            string configText = BuildDefaultConfiguration(AppSettingsService.Instance.MixedPort, mode);
            File.WriteAllText(_configurationFilePath, configText, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            return GetState();
        }
    }

    /// <summary>Builds a minimal safe mihomo configuration text for local startup probing.</summary>
    /// <param name="mixedPort">Mixed HTTP and SOCKS proxy port in range [1, 65535].</param>
    /// <param name="mode">Master takeover mode whose equivalent mihomo mode should be emitted.</param>
    /// <returns>YAML configuration text with deterministic line endings.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="mixedPort"/> is outside the valid TCP port range.</exception>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="mode"/> cannot be mapped to a mihomo mode.</exception>
    private static string BuildDefaultConfiguration(int mixedPort, ClashSharpMode mode)
    {
        if (mixedPort is < 1 or > 65535)
        {
            throw new ArgumentOutOfRangeException(nameof(mixedPort), "Port must be in the range [1, 65535].");
        }

        string mihomoMode = MapToMihomoMode(mode);

        return string.Join(
            "\n",
            [
                "# Generated by Clash#.",
                "# This minimal configuration is overwritten when a profile is selected.",
                $"mixed-port: {mixedPort.ToString(CultureInfo.InvariantCulture)}",
                "allow-lan: false",
                $"mode: {mihomoMode}",
                "log-level: info",
                "external-controller: 127.0.0.1:9090",
                "ipv6: true",
                "profile:",
                "  store-selected: true",
                "  store-fake-ip: true",
                "proxies: []",
                "proxy-groups:",
                "  - name: GLOBAL",
                "    type: select",
                "    proxies:",
                "      - DIRECT",
                "  - name: DIRECT",
                "    type: select",
                "    proxies:",
                "      - DIRECT",
                "rules:",
                "  - MATCH,DIRECT",
                string.Empty,
            ]);
    }

    /// <summary>Maps a Clash# master takeover mode to a mihomo configuration mode.</summary>
    /// <param name="mode">Master takeover mode to map.</param>
    /// <returns>The mihomo mode string used in configuration YAML.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="mode"/> cannot be mapped to a mihomo mode.</exception>
    private static string MapToMihomoMode(ClashSharpMode mode)
    {
        return mode switch
        {
            ClashSharpMode.Disabled or ClashSharpMode.Standby => "direct",
            ClashSharpMode.RuleTakeover => "rule",
            ClashSharpMode.FullTakeover => "global",
            _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, "Unsupported Clash# configuration mode."),
        };
    }

    /// <summary>Resolves the directory used for local application records.</summary>
    /// <returns>Absolute directory path for local application data; never null.</returns>
    private static string ResolveDataDirectory()
    {
        try
        {
            return ApplicationData.Current.LocalFolder.Path;
        }
        catch (InvalidOperationException)
        {
            return Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "ClashSharp");
        }
    }
}
