using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using ClashSharp.Model;
using YamlDotNet.Core;
using YamlDotNet.RepresentationModel;

namespace ClashSharp.Service;

/// <summary>Builds deterministic mihomo runtime configuration controlled by Clash#.</summary>
/// <remarks>
/// Invariants: Imported profiles are overlaid through a semantic YAML mapping, generated text uses
/// LF line endings, and only Clash# selects controller, listener, mode, port, and TUN fields.
/// Thread safety: Stateless methods are safe for concurrent calls.
/// Side effects: None.
/// </remarks>
internal static class MihomoRuntimeConfigurationBuilder
{
    /// <summary>Builds a minimal safe mihomo configuration for local startup.</summary>
    public static string BuildDefaultConfiguration(
        int mixedPort,
        ClashSharpMode mode,
        bool transparentProxyEnabled,
        string controllerSecret)
    {
        ValidateMixedPort(mixedPort);
        ValidateControllerSecret(controllerSecret);

        List<string> lines =
        [
            "# Generated by Clash#.",
            "# This minimal configuration is overwritten when a profile is selected.",
            $"mixed-port: {mixedPort.ToString(CultureInfo.InvariantCulture)}",
            "allow-lan: false",
            "bind-address: 127.0.0.1",
            $"mode: {MapToMihomoMode(mode)}",
            "log-level: info",
            $"external-controller: {MihomoControllerEndpoint.ListenAddress}",
            $"secret: '{controllerSecret}'",
            "ipv6: true",
        ];

        if (transparentProxyEnabled)
        {
            AppendTunConfiguration(lines);
            AppendManagedDnsConfiguration(lines);
        }

        lines.AddRange(
        [
            "profile:",
            "  store-selected: true",
            "  store-fake-ip: true",
            "proxies: []",
            "proxy-groups:",
            "  - name: GLOBAL",
            "    type: select",
            "    proxies:",
            "      - DIRECT",
            "  - name: DIRECT",
            "    type: select",
            "    proxies:",
            "      - DIRECT",
            "rules:",
            "  - MATCH,DIRECT",
            string.Empty,
        ]);

        string configurationText = string.Join("\n", lines);
        MihomoYamlSemanticValidator.ValidateManagedRuntimeConfiguration(
            configurationText,
            mixedPort,
            mode,
            transparentProxyEnabled,
            controllerSecret);
        return configurationText;
    }

    /// <summary>Overlays Clash#-owned runtime fields on an imported profile YAML mapping.</summary>
    public static string OverrideRuntimeKeys(
        string configurationText,
        int mixedPort,
        ClashSharpMode mode,
        bool transparentProxyEnabled,
        string controllerSecret)
    {
        ArgumentNullException.ThrowIfNull(configurationText);
        ValidateMixedPort(mixedPort);
        ValidateControllerSecret(controllerSecret);

        YamlMappingNode importedRoot = MihomoYamlSemanticValidator.LoadUniqueRootMappingNode(
            configurationText,
            nameof(configurationText));
        YamlMappingNode managedRoot = new();
        AddManagedRuntimeFields(
            managedRoot,
            mixedPort,
            mode,
            transparentProxyEnabled,
            controllerSecret);

        foreach ((YamlNode keyNode, YamlNode valueNode) in importedRoot.Children)
        {
            YamlScalarNode scalarKey = (YamlScalarNode)keyNode;
            if (!MihomoYamlSemanticValidator.IsAppOwnedRuntimeKey(scalarKey.Value!))
            {
                managedRoot.Add(keyNode, valueNode);
            }
        }

        if (transparentProxyEnabled)
        {
            EnsureTunDnsConfiguration(managedRoot);
        }

        YamlStream managedStream = new(new YamlDocument(managedRoot));
        using StringWriter writer = new(CultureInfo.InvariantCulture);
        managedStream.Save(writer, assignAnchors: true);
        string managedConfigurationText = NormalizeConfigurationText(writer.ToString());
        MihomoYamlSemanticValidator.ValidateManagedRuntimeConfiguration(
            managedConfigurationText,
            mixedPort,
            mode,
            transparentProxyEnabled,
            controllerSecret);
        return managedConfigurationText;
    }

    /// <summary>Returns whether TUN is effective for a selected master mode and preference.</summary>
    public static bool ShouldEnableTransparentProxy(ClashSharpMode mode, bool transparentProxyEnabled)
    {
        return transparentProxyEnabled && mode is ClashSharpMode.RuleTakeover or ClashSharpMode.FullTakeover;
    }

    /// <summary>Maps a Clash# master takeover mode to a mihomo runtime mode.</summary>
    public static string MapToMihomoMode(ClashSharpMode mode)
    {
        return mode switch
        {
            ClashSharpMode.Disabled or ClashSharpMode.Standby => "direct",
            ClashSharpMode.RuleTakeover => "rule",
            ClashSharpMode.FullTakeover => "global",
            _ => throw new ArgumentOutOfRangeException(nameof(mode), mode, "Unsupported Clash# configuration mode."),
        };
    }

    /// <summary>Normalizes line endings and ensures one trailing line break.</summary>
    public static string NormalizeConfigurationText(string configurationText)
    {
        ArgumentNullException.ThrowIfNull(configurationText);
        string normalized = configurationText
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n')
            .Trim();
        return normalized + "\n";
    }

    private static void AddManagedRuntimeFields(
        YamlMappingNode root,
        int mixedPort,
        ClashSharpMode mode,
        bool transparentProxyEnabled,
        string controllerSecret)
    {
        root.Add(PlainScalar("external-controller"), PlainScalar(MihomoControllerEndpoint.ListenAddress));
        root.Add(
            PlainScalar("secret"),
            new YamlScalarNode(controllerSecret)
            {
                Style = ScalarStyle.SingleQuoted,
            });
        root.Add(PlainScalar("allow-lan"), PlainScalar("false"));
        root.Add(PlainScalar("bind-address"), PlainScalar("127.0.0.1"));
        root.Add(PlainScalar("mode"), PlainScalar(MapToMihomoMode(mode)));
        root.Add(
            PlainScalar("mixed-port"),
            PlainScalar(mixedPort.ToString(CultureInfo.InvariantCulture)));
        root.Add(PlainScalar("log-level"), PlainScalar("info"));
        if (transparentProxyEnabled)
        {
            root.Add(PlainScalar("tun"), BuildTunConfiguration());
        }
    }

    private static YamlMappingNode BuildTunConfiguration()
    {
        YamlMappingNode tun = new();
        tun.Add(PlainScalar("enable"), PlainScalar("true"));
        tun.Add(PlainScalar("stack"), PlainScalar("system"));
        tun.Add(PlainScalar("auto-route"), PlainScalar("true"));
        tun.Add(PlainScalar("auto-detect-interface"), PlainScalar("true"));
        tun.Add(PlainScalar("strict-route"), PlainScalar("false"));
        tun.Add(
            PlainScalar("dns-hijack"),
            new YamlSequenceNode(PlainScalar("any:53")));
        return tun;
    }

    private static YamlMappingNode BuildManagedDnsConfiguration()
    {
        YamlMappingNode dns = new();
        dns.Add(PlainScalar("enable"), PlainScalar("true"));
        dns.Add(PlainScalar("enhanced-mode"), PlainScalar("fake-ip"));
        dns.Add(
            PlainScalar("default-nameserver"),
            new YamlSequenceNode(
                PlainScalar("223.5.5.5"),
                PlainScalar("1.1.1.1")));
        dns.Add(
            PlainScalar("nameserver"),
            new YamlSequenceNode(
                PlainScalar("https://dns.alidns.com/dns-query"),
                PlainScalar("https://1.1.1.1/dns-query")));
        return dns;
    }

    private static void EnsureTunDnsConfiguration(YamlMappingNode root)
    {
        if (!TryGetScalarKeyValue(root, "dns", out YamlNode? dnsNode))
        {
            root.Add(PlainScalar("dns"), BuildManagedDnsConfiguration());
            return;
        }

        if (dnsNode is not YamlMappingNode dns)
        {
            throw new ArgumentException("Transparent proxy DNS configuration must be a mapping.");
        }

        if (!TryGetScalarKeyValue(dns, "enable", out _))
        {
            dns.Add(PlainScalar("enable"), PlainScalar("true"));
        }

        if (!TryGetScalarKeyValue(dns, "enhanced-mode", out _))
        {
            dns.Add(PlainScalar("enhanced-mode"), PlainScalar("fake-ip"));
        }

        if (!TryGetScalarKeyValue(dns, "default-nameserver", out _))
        {
            dns.Add(
                PlainScalar("default-nameserver"),
                new YamlSequenceNode(
                    PlainScalar("223.5.5.5"),
                    PlainScalar("1.1.1.1")));
        }

        if (!TryGetScalarKeyValue(dns, "nameserver", out _))
        {
            dns.Add(
                PlainScalar("nameserver"),
                new YamlSequenceNode(
                    PlainScalar("https://dns.alidns.com/dns-query"),
                    PlainScalar("https://1.1.1.1/dns-query")));
        }
    }

    private static bool TryGetScalarKeyValue(
        YamlMappingNode mapping,
        string expectedKey,
        out YamlNode? value)
    {
        foreach ((YamlNode keyNode, YamlNode valueNode) in mapping.Children)
        {
            if (keyNode is YamlScalarNode key
                && StringComparer.Ordinal.Equals(key.Value, expectedKey))
            {
                value = valueNode;
                return true;
            }
        }

        value = null;
        return false;
    }

    private static YamlScalarNode PlainScalar(string value)
    {
        return new YamlScalarNode(value)
        {
            Style = ScalarStyle.Plain,
        };
    }

    private static void AppendTunConfiguration(ICollection<string> lines)
    {
        lines.Add("tun:");
        lines.Add("  enable: true");
        lines.Add("  stack: system");
        lines.Add("  auto-route: true");
        lines.Add("  auto-detect-interface: true");
        lines.Add("  strict-route: false");
        lines.Add("  dns-hijack:");
        lines.Add("    - any:53");
    }

    private static void AppendManagedDnsConfiguration(ICollection<string> lines)
    {
        lines.Add("dns:");
        lines.Add("  enable: true");
        lines.Add("  enhanced-mode: fake-ip");
        lines.Add("  default-nameserver:");
        lines.Add("    - 223.5.5.5");
        lines.Add("    - 1.1.1.1");
        lines.Add("  nameserver:");
        lines.Add("    - https://dns.alidns.com/dns-query");
        lines.Add("    - https://1.1.1.1/dns-query");
    }

    private static void ValidateMixedPort(int mixedPort)
    {
        if (mixedPort is < 1 or > 65535)
        {
            throw new ArgumentOutOfRangeException(nameof(mixedPort), "Port must be in the range [1, 65535].");
        }
    }

    private static void ValidateControllerSecret(string controllerSecret)
    {
        ArgumentNullException.ThrowIfNull(controllerSecret);
        if (!MihomoControllerEndpoint.IsValidSecret(controllerSecret))
        {
            throw new ArgumentException(
                "Controller secret must be a 256-bit lowercase hexadecimal value.",
                nameof(controllerSecret));
        }
    }
}
